name: "Synapse Login"
branding:
  icon: 'log-in'
  color: 'blue'
description: "Log into Synapse"

inputs:
  username:
    description: "Synapse username"
    required: true

  apikey:
    description: "Synapse apikey"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"