name: ci

on:
  push:
    branches:
      - main

jobs:

  fail_login:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: synapse PAT login
      uses: ./
      with:
        username: ${{ secrets.SYNAPSE_USERNAME }}

  apikey_login:
    runs-on: ubuntu-20.04
    needs: test_login
    if: ${{ failure() }}
    steps:
    - uses: actions/checkout@v2
    - name: synapse api login
      uses: ./
      with:
        username: ${{ secrets.SYNAPSE_USERNAME }}
        apikey: ${{ secrets.SYNAPSE_APIKEY }}

  pat_login:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: synapse PAT login
      uses: ./
      with:
        username: ${{ secrets.SYNAPSE_USERNAME }}
        pat: ${{ secrets.SYNAPSE_PAT }}
